# Install these with `pre-commit install`
# Run yourself with `pre-commit run`.
# See https://pre-commit.com for more information
repos:
# Keep linter versions here in sync with the versions in poetry.lock.
- repo: https://github.com/floatingpurr/sync_with_poetry
  rev: '1.2.1'
  hooks:
    - id: sync_with_poetry

- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.5.7
  hooks:
    # Run the linter.
    - id: ruff
      args: [ '--fix' ]
      files: '^(src|tests)/'
    # Run the formatter.
    - id: ruff-format
      files: '^(src|tests)/'

- repo: https://github.com/pycqa/isort
  rev: 5.13.2
  hooks:
    - id: isort
      name: isort (python)
      files: '^(src|tests)/'

# Using this mirror lets us use mypyc-compiled black, which is about 2x faster
- repo: https://github.com/psf/black-pre-commit-mirror
  rev: 22.6.0
  hooks:
    - id: black
      language_version: python3.10
      files: '^(src|tests)/'